use_frameworks!

platform :ios, '8.0'

target 'WLButtonGridView_Example' do
    
#  pod 'YYCategories'
#  pod 'SDWebImage', '~> 4.0'
  pod 'WLButtonGridView', :path => '../'

  target 'WLButtonGridView_Tests' do
    inherit! :search_paths

    
  end
end
